# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run-evaluation:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install miniconda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.10.3-Linux-x86_64.sh
          bash Miniconda3-py37_4.10.3-Linux-x86_64.sh -b -p $HOME/miniconda

      - name: prepare venv
        run: |
          conda create -y --name icdcoder python=3.7.3 
          conda activate icdcoder
          pip install --upgrade pip
          cd icdcoder
          pip install -r requirements.txt
          cp ~/data/Stockholm-EPR-Gastro-ICD-10-Pseudo-Corpus-v2/fine_tuned_model/pytorch_model.bin ~/work/icdcoder/models/fine_tuned_model/
      - name: run model evaluation
        run: python3 BERT_coder.py -test_file "~/data/Stockholm-EPR-Gastro-ICD-10-Pseudo-Corpus-v2/Blocks-pseudo/210414_above3_pseudo_210622.csv" 
